version: '3.9'

services:
  api:
    image: node:18.14.2
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      NODE_ENV: local
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c 'npm install && npm run start'
