version: '3.9'

services:
  api:
    image: node:18.14.2
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      NODE_ENV: local
    env_file:
      - ./.env
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      mysql:
        condition: service_healthy
    command: sh -c 'npm install && npm run start'

  mysql:
    image: mysql:8.0.32
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: express-typescript-todo-api
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 2s
      retries: 10

volumes:
  mysqldata:
